import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL ?? `${window.location.protocol}//${window.location.hostname}:5000`;
const tabs = ['Overview', 'Grid topology', 'Alerts', 'Command center', 'Performance'];

function formatNumber(value, digits = 0) {
  return Number(value ?? 0).toLocaleString(undefined, { maximumFractionDigits: digits });
}

function Sparkline({ values, color = '#7fffc0' }) {
  if (!values.length) return <div className="chart-empty">Waiting for telemetry...</div>;
  const max = Math.max(...values, 1); const min = Math.min(...values, 0); const range = max - min || 1;
  const points = values.map((value, index) => `${(index / Math.max(values.length - 1, 1)) * 100},${100 - ((value - min) / range) * 88 - 6}`).join(' ');
  return <svg className="sparkline" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Power consumption trend"><polyline points={points} fill="none" stroke={color} strokeWidth="2" vectorEffect="non-scaling-stroke" /></svg>;
}

function MetricCard({ label, value, unit, tone = 'normal', detail }) {
  return <article className={`metric-card ${tone}`}><div className="metric-label">{label}</div><div className="metric-value">{value}<small>{unit}</small></div>{detail && <div className="metric-detail">{detail}</div>}</article>;
}

function Login({ onLogin, onClose }) {
  const [username, setUsername] = useState('operator'); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  async function submit(event) { event.preventDefault(); setError(''); setSubmitting(true); try { const result = await onLogin(username, password); if (!result) setError('Invalid credentials or API unavailable.'); } finally { setSubmitting(false); } }
  return <div className="modal-backdrop"><form className="login-card" onSubmit={submit}><button type="button" className="modal-close" onClick={onClose} aria-label="Close sign-in dialog">x</button><span className="eyebrow">OPERATOR AUTHENTICATION</span><h2>Command access</h2><p>Sign in to operate virtual breakers and manage alerts.</p><label>Username<input value={username} autoComplete="username" onChange={(event) => setUsername(event.target.value)} /></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{error && <div className="form-error" role="alert">{error}</div>}<button className="primary-button" type="submit" disabled={submitting}>{submitting ? 'AUTHENTICATING...' : 'AUTHENTICATE'}</button></form></div>;
}

function Overview({ metrics, powerHistory, sensors, alerts, systemStatus }) {
  const online = metrics.onlineSensors ?? 0; const active = metrics.activeSensors ?? 0;
  const dependencies = systemStatus.dependencies ?? {};
  const dependencyRows = [['MQTT pipeline', dependencies.mqtt], ['Redis state', dependencies.redis], ['Database writer', dependencies.database]];
  return <><section className="metric-grid"><MetricCard label="Total active power" value={formatNumber(metrics.totalPower ?? 0)} unit=" W" detail="Across reporting grids" /><MetricCard label="Online sensors" value={formatNumber(online)} unit={` / ${formatNumber(active)}`} detail={`${formatNumber(metrics.offlineSensors)} offline`} tone={metrics.offlineSensors ? 'warning' : 'normal'} /><MetricCard label="Active alerts" value={formatNumber(alerts.length)} unit="" detail="Live safety conditions" tone={alerts.length ? 'critical' : 'normal'} /><MetricCard label="Messages per second" value={formatNumber(metrics.messagesPerSecond)} unit=" msg/s" detail={`${formatNumber(metrics.processedPerSecond)} processed`} /></section><section className="dashboard-grid"><article className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">LIVE TELEMETRY</span><h2>Power consumption</h2></div><span className="live-badge"><i></i> STREAMING</span></div><div className="chart-value">{formatNumber(powerHistory.at(-1) ?? 0)} <small>W current sample</small></div><Sparkline values={powerHistory} /><div className="chart-axis"><span>60 sec ago</span><span>now</span></div></article><article className="panel health-panel"><div className="panel-heading"><div><span className="eyebrow">GRID HEALTH</span><h2>System posture</h2></div></div><div className="health-ring"><strong>{alerts.length || systemStatus.status === 'degraded' ? 'WARN' : 'GOOD'}</strong><span>{alerts.length ? 'Attention required' : 'Live dependency status'}</span></div><div className="health-list">{dependencyRows.map(([label, state]) => <div key={label}><span className={`dot ${state === 'CONNECTED' ? 'green' : 'yellow'}`}></span> {label} <b>{state ?? 'UNKNOWN'}</b></div>)}</div></article></section><section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">LATEST READINGS</span><h2>Sensor telemetry</h2></div><span className="table-count">{formatNumber(sensors.length)} devices</span></div><div className="table-wrap"><table><thead><tr><th>Sensor</th><th>Grid</th><th>Power</th><th>Voltage</th><th>Frequency</th><th>Temperature</th><th>Status</th></tr></thead><tbody>{sensors.slice(0, 12).map((sensor) => <tr key={sensor.sensorId}><td className="mono">{sensor.sensorId}</td><td>{sensor.gridId}</td><td>{formatNumber(sensor.power, 1)} W</td><td>{formatNumber(sensor.voltage, 1)} V</td><td>{formatNumber(sensor.frequency, 2)} Hz</td><td>{formatNumber(sensor.temperature, 1)} C</td><td><span className={`status-pill ${String(sensor.status).toLowerCase()}`}>{sensor.status}</span></td></tr>)}{!sensors.length && <tr><td colSpan="7" className="empty-cell">Waiting for simulator telemetry...</td></tr>}</tbody></table></div></section></>;
}

function Topology({ grids }) {
  return <section className="panel topology-panel"><div className="panel-heading"><div><span className="eyebrow">NETWORK TOPOLOGY</span><h2>Virtual distribution grid</h2></div><span className="status-pill online">LIVE</span></div><div className="topology-root"><div className="topology-node root-node"><span className="node-icon">+</span><b>MAIN GRID</b><small>REGION-01</small></div><div className="topology-line"></div><div className="topology-branches">{grids.slice(0, 12).map((grid) => <div className="grid-node" key={grid.gridId}><span className="node-icon">G</span><div><b>{grid.name ?? grid.gridId}</b><small>{grid.gridId} / {formatNumber(grid.totalPower, 0)} W</small></div><span className="dot green"></span></div>)}</div>{!grids.length && <div className="empty-cell">Grid nodes appear when telemetry is received.</div>}</div></section>;
}

function Alerts({ alerts, token, onLogin, onAcknowledge }) {
  return <section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">SAFETY MONITORING</span><h2>Active alerts</h2></div><span className={`status-pill ${alerts.length ? 'critical' : 'online'}`}>{alerts.length ? `${alerts.length} ACTIVE` : 'NOMINAL'}</span></div><div className="alert-list">{alerts.map((alert) => <div className="alert-row" key={alert.id}><span className={`severity ${String(alert.severity).toLowerCase()}`}>{alert.severity}</span><div><b>{alert.type.replaceAll('_', ' ')}</b><p>{alert.message}</p><small>{alert.sensorId} / {alert.gridId} - {new Date(alert.timestamp).toLocaleTimeString()}</small></div>{alert.status === 'ACTIVE' && <button className="secondary-button" onClick={() => token ? onAcknowledge(alert.id) : onLogin()}>ACKNOWLEDGE</button>}</div>)}{!alerts.length && <div className="empty-state"><span className="node-icon">OK</span><h3>No active alerts</h3><p>Safety rules are being evaluated against live telemetry.</p></div>}</div></section>;
}

function CommandCenter({ breakers, token, onLogin, onCommand }) {
  return <section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">CONTROL AUTHORITY</span><h2>Virtual breaker command center</h2></div><span className="status-pill online">SOFTWARE ONLY</span></div><p className="panel-note">Commands are sent through MQTT and confirmed by the simulator status topic.</p><div className="breaker-grid">{breakers.map((breaker) => <div className="breaker-card" key={breaker.breakerId}><div className="breaker-top"><div><b>{breaker.breakerId}</b><small>{breaker.gridId}</small></div><span className={`status-pill ${String(breaker.status).toLowerCase()}`}>{breaker.status}</span></div><div className="breaker-actions">{['ON', 'OFF', 'TRIP', 'RESET'].map((action) => <button key={action} className={action === 'TRIP' ? 'danger-button' : 'secondary-button'} onClick={() => token ? onCommand(breaker.breakerId, action) : onLogin()}>{action}</button>)}</div></div>)}{!breakers.length && <div className="empty-cell">Breaker inventory is initializing.</div>}</div></section>;
}

function Performance({ metrics, powerHistory }) {
  return <><section className="metric-grid performance-metrics"><MetricCard label="Average latency" value={formatNumber(metrics.processingLatencyMs?.average, 2)} unit=" ms" /><MetricCard label="P95 latency" value={formatNumber(metrics.processingLatencyMs?.p95, 2)} unit=" ms" /><MetricCard label="Redis updates" value={formatNumber(metrics.redisUpdates)} unit="" /><MetricCard label="Database batches" value={formatNumber(metrics.databaseWrites)} unit="" /></section><section className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">THROUGHPUT OBSERVABILITY</span><h2>Live message rate</h2></div><span className="metric-value compact">{formatNumber(metrics.messagesPerSecond)}<small> msg/s</small></span></div><Sparkline values={powerHistory.map((value, index) => (metrics.messagesPerSecond || 0) + Math.sin(index) * 0)} color="#67d9ff" /><div className="performance-foot"><span>Target: configurable sensor fleet</span><span>Processed: {formatNumber(metrics.processed)} total</span><span>Dropped: {formatNumber(metrics.dropped)}</span><span>Pending DB aggregates: {formatNumber(metrics.pendingAggregates)}</span></div></section></>;
}

function App() {
  const [tab, setTab] = useState('Overview'); const [metrics, setMetrics] = useState({}); const [sensors, setSensors] = useState([]); const [grids, setGrids] = useState([]); const [breakers, setBreakers] = useState([]); const [alerts, setAlerts] = useState([]); const [powerHistory, setPowerHistory] = useState([]); const [showLogin, setShowLogin] = useState(false); const [token, setToken] = useState(() => localStorage.getItem('gridops_token') ?? ''); const [connection, setConnection] = useState('CONNECTING'); const [systemStatus, setSystemStatus] = useState({}); const [now, setNow] = useState(() => new Date()); const reconnectTimer = useRef();
  const load = async () => { try { const responses = await Promise.all(['metrics', 'sensors?limit=100', 'grids', 'breakers', 'alerts', 'system/status'].map((path) => fetch(`${API}/api/${path}`))); if (responses.some((response) => !response.ok)) throw new Error('One or more dashboard requests failed'); const [metricData, sensorData, gridData, breakerData, alertData, statusData] = await Promise.all(responses.map((response) => response.json())); setMetrics(metricData); setPowerHistory((history) => [...history.slice(-59), Number(metricData.totalPower ?? metricData.messagesPerSecond ?? 0)]); setSensors(sensorData); setGrids(gridData); setBreakers(breakerData); setAlerts(alertData); setSystemStatus(statusData); setConnection('CONNECTED'); } catch { setConnection('DEGRADED'); } };
  useEffect(() => { load(); const timer = setInterval(load, 2000); return () => clearInterval(timer); }, []);
  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 30_000); return () => clearInterval(timer); }, []);
  useEffect(() => { let disposed = false; let socket; const connect = () => { socket = new WebSocket(`${API.replace(/^http/, 'ws')}/ws`); socket.onopen = () => setConnection('CONNECTED'); socket.onclose = () => { if (!disposed) { setConnection('DEGRADED'); reconnectTimer.current = setTimeout(connect, 3000); } }; socket.onmessage = (event) => { try { const message = JSON.parse(event.data); if (message.type === 'system_metrics') setMetrics(message.payload); if (message.type === 'telemetry_update') setSensors((current) => [message.payload, ...current.filter((sensor) => sensor.sensorId !== message.payload.sensorId)].slice(0, 100)); if (message.type === 'breaker_status') setBreakers((current) => [...current.filter((breaker) => breaker.breakerId !== message.payload.breakerId), message.payload]); if (message.type === 'alert_created') setAlerts((current) => [...current.filter((alert) => alert.id !== message.payload.id), message.payload]); if (message.type === 'alert_resolved') setAlerts((current) => current.filter((alert) => alert.id !== message.payload.id)); } catch { /* ignore malformed websocket frames */ } }; }; connect(); return () => { disposed = true; clearTimeout(reconnectTimer.current); socket?.close(); }; }, []);
  async function login(username, password) { try { const response = await fetch(`${API}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username, password }) }); if (!response.ok) return false; const result = await response.json(); localStorage.setItem('gridops_token', result.token); setToken(result.token); setShowLogin(false); return true; } catch { return false; } }
  async function command(breakerId, action) { const response = await fetch(`${API}/api/breakers/${breakerId}/${action.toLowerCase()}`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) { setShowLogin(true); return; } }
  async function acknowledge(alertId) { const response = await fetch(`${API}/api/alerts/${alertId}/acknowledge`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) setShowLogin(true); }
  const page = useMemo(() => ({ Overview: <Overview metrics={metrics} powerHistory={powerHistory} sensors={sensors} alerts={alerts} systemStatus={systemStatus} />, 'Grid topology': <Topology grids={grids} />, Alerts: <Alerts alerts={alerts} token={token} onLogin={() => setShowLogin(true)} onAcknowledge={acknowledge} />, 'Command center': <CommandCenter breakers={breakers} token={token} onLogin={() => setShowLogin(true)} onCommand={command} />, Performance: <Performance metrics={metrics} powerHistory={powerHistory} /> }[tab]), [tab, metrics, powerHistory, sensors, alerts, grids, breakers, token, systemStatus]);
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">G</span><div><b>GRIDOPS</b><small>ENERGY CONTROL</small></div></div><div className="side-label">OPERATIONS</div><nav aria-label="Dashboard sections">{tabs.map((item) => <button key={item} className={tab === item ? 'active' : ''} aria-current={tab === item ? 'page' : undefined} onClick={() => setTab(item)}><span className="nav-icon">{['+','/','!','>','~'][tabs.indexOf(item)]}</span>{item}</button>)}</nav><div className="sidebar-footer"><span className={`dot ${connection === 'CONNECTED' ? 'green' : 'yellow'}`}></span><div><b>{connection}</b><small>Local control plane</small></div></div></aside><main className="main-content"><header className="topbar"><div><span className="eyebrow">SMART GRID / CONTROL ROOM</span><h1>{tab}</h1></div><div className="topbar-actions"><span className="clock">{now.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}</span>{token ? <button className="user-chip" onClick={() => { localStorage.removeItem('gridops_token'); setToken(''); }}>OPERATOR <span>LOG OUT</span></button> : <button className="primary-button small" onClick={() => setShowLogin(true)}>SIGN IN</button>}</div></header><div className="content">{page}</div></main>{showLogin && <Login onLogin={login} onClose={() => setShowLogin(false)} />}</div>;
}

createRoot(document.getElementById('root')).render(<App />);
